//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 07:43:38 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://namaraka.com/ggserver/config/v1_0")
package com.namaraka.ggserver.config.v1_0;
