package com.namaraka.ggserver.model.v1_0;

import com.namaraka.ggserver.constant.Status;
import com.namaraka.ggserver.utils.Auditable;
import com.namaraka.ggserver.utils.DBMSXMLObject;
import java.io.Serializable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.SelectBeforeUpdate;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;
import org.joda.time.DateTime;
import org.jadira.usertype.dateandtime.joda.PersistentLocalDateTime;
import org.joda.time.LocalDateTime;

@TypeDefs({
    @TypeDef(name = "jodalocaldatetime", typeClass = PersistentLocalDateTime.class,
            parameters = {
                @Parameter(value = "UTC", name = "databaseZone"),
                @Parameter(value = "UTC", name = "javaZone")
            }
    )
})

@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "transactions")

public class MoMoTransaction extends BaseModel implements Auditable, Serializable {

    private static final long serialVersionUID = 4420429742816294897L;

    private String customerMsisdn;
    @Type(type = "jodalocaldatetime")
    //private LocalDateTime creationDate;//from app end
    private String invoiceNumber; //number issued by app to initiate payment
    private String cmsTransactionID; //ID generated by the CMS for this transaction
    private String aggregatorTransID; //transaction ID issued by aggregator
    private String recieptNumber; //ID issued by MNO after user confirms payment
    @Embedded
    private Amounttype amount; //initialise this to do away with null pointers
    private String payerNarration;
    private String debitAccount; //Mobile Money account to debit

    //@Type(type = "jodalocaldatetime")
    private LocalDateTime approvalDate;
    @Enumerated(EnumType.STRING)
    private Status status;
    private String statusDescription;
    @Embedded
    private Extensiontype extensionType;

    @Transient
    private String typename;
    private String version;

    /**
     * Gets the value of the extensionType property.
     *
     * @return possible object is {@link Credentialstype }
     *
     */
    public Extensiontype getExtensionType() {
        return extensionType;
    }

    /**
     * Sets the value of the extensionType property.
     *
     * @param value allowed object is {@link Credentialstype }
     *
     */
    public void setExtensionType(Extensiontype value) {
        this.extensionType = value;
    }

    public boolean isExtensionType() {
        return (this.getExtensionType() != null);
    }

    /**
     * Gets the value of the msisdn property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCustomerMsisdn() {
        return customerMsisdn;
    }

    /**
     * Sets the value of the customerMsisdn property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCustomerMsisdn(String value) {
        this.customerMsisdn = value;
    }

    public boolean isSetCustomermsisdn() {
        return (this.getCustomerMsisdn() != null);
    }

    /**
     * Gets the value of the amount property.
     *
     * @return possible object is {@link Amounttype }
     *
     */
    public Amounttype getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     *
     * @param value allowed object is {@link Amounttype }
     *
     */
    public void setAmount(Amounttype value) {
        this.amount = value;
    }

    public boolean isSetAmount() {
        return (this.getAmount() != null);
    }

    /**
     * Gets the value of the payerNarration property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPayerNarration() {
        return payerNarration;
    }

    /**
     * Sets the value of the payerNarration property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPayerNarration(String value) {
        this.payerNarration = value;
    }

    public boolean isSetPaymentnarration() {
        return (this.getPayerNarration() != null);
    }

    /**
     * Gets the value of the debitAccount property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDebitAccount() {
        return debitAccount;
    }

    /**
     * Sets the value of the debitAccount property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDebitAccount(String value) {
        this.debitAccount = value;
    }

    public boolean isSetCustomeridentity() {
        return (this.getDebitAccount() != null);
    }

    /**
     * Gets the value of the invoiceNumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    public boolean isSetInvoiceNumber() {
        return (this.getInvoiceNumber() != null);
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is {@link Statustype }
     *
     */
    public Status getTransactionstatus() {
        return getStatus();
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is {@link Statustype }
     *
     */
    public void setTransactionstatus(Status value) {
        this.setStatus(value);
    }

    public boolean isSetTransactionstatus() {
        return (this.getStatus() != null);
    }

    /**
     * Gets the value of the statusDescription property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStatusDescription() {
        return statusDescription;
    }

    /**
     * Sets the value of the statusDescription property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setStatusDescription(String value) {
        this.statusDescription = value;
    }

    public boolean isSetCollectionsaccount() {
        return (this.getStatusDescription() != null);
    }


    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.getVersion() != null);
    }

    /**
     * Gets the value of the typename property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTypename() {
        if (typename == null) {
            return "servicerequest";
        } else {
            return typename;
        }
    }

    /**
     * Sets the value of the typename property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTypename(String value) {
        this.typename = value;
    }

    public boolean isSetTypename() {
        return (this.getTypename() != null);
    }

    /**
     * @return the approvalDate
     */
    public LocalDateTime getApprovalDate() {
        return approvalDate;
    }

    /**
     * @param approvalDate the approvalDate to set
     */
    public void setApprovalDate(LocalDateTime approvalDate) {
        this.approvalDate = approvalDate;
    }

    /**
     * @return the aggregatorTransID
     */
    public String getAggregatorTransID() {
        return aggregatorTransID;
    }

    /**
     * @param aggregatorTransID the aggregatorTransID to set
     */
    public void setAggregatorTransID(String aggregatorTransID) {
        this.aggregatorTransID = aggregatorTransID;
    }

    /**
     * @return the recieptNumber
     */
    public String getRecieptNumber() {
        return recieptNumber;
    }

    /**
     * @param recieptNumber the recieptNumber to set
     */
    public void setRecieptNumber(String recieptNumber) {
        this.recieptNumber = recieptNumber;
    }

    /**
     * @return the status
     */
    public Status getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    public String getCmsTransactionID() {
        return cmsTransactionID;
    }

    public void setCmsTransactionID(String cmsTransactionID) {
        this.cmsTransactionID = cmsTransactionID;
    }

    @Override
    public DBMSXMLObject getXMLObject() {
        return this;
    }

    @Override
    public String getUsername() {
        return "hardcoded user";
    }

    // This ensures that a check is always performed when the model is saved, 
    //instead of having to manually add the check to every piece of code that saves the model.
//    @PrePersist
//    public void prepareToInsert() {//cant we do this check inside the Interceptor
//        List<Servicerequest> conflicts = find("user=?").fetch();
//        if (!conflicts.isEmpty()) {
//            throw new MyCustomException("username `" + name + "` already exists");
//        }
//    }
}
