//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 07:43:38 PM EAT 
//


package com.namaraka.ggserver.model.v1_0;

import com.namaraka.ggserver.config.v1_0.Appconfig;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.com.cellulant.aopc.config.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.com.cellulant.aopc.config.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Appconfig }
     * 
     */
    public Appconfig createAppconfig() {
        return new Appconfig();
    }

    /**
     * Create an instance of {@link Appconfig.Schedulers }
     * 
     */
    public Appconfig.Schedulers createAppconfigSchedulers() {
        return new Appconfig.Schedulers();
    }

    /**
     * Create an instance of {@link Appconfig.Managermethods }
     * 
     */
    public Appconfig.Managermethods createAppconfigManagermethods() {
        return new Appconfig.Managermethods();
    }

    /**
     * Create an instance of {@link Appconfig.Nodenames }
     * 
     */
    public Appconfig.Nodenames createAppconfigNodenames() {
        return new Appconfig.Nodenames();
    }

    /**
     * Create an instance of {@link Appconfig.Internalmethods }
     * 
     */
    public Appconfig.Internalmethods createAppconfigInternalmethods() {
        return new Appconfig.Internalmethods();
    }

    /**
     * Create an instance of {@link Appconfig.Integrationmethods }
     * 
     * @return 
     */
    public Appconfig.Integrationmethods createAppconfigIntegrationmethods() {
        return new Appconfig.Integrationmethods();
    }

    /**
     * Create an instance of {@link Appconfig.Allowedips }
     * 
     * @return 
     */
    public Appconfig.Allowedips createAppconfigAllowedips() {
        return new Appconfig.Allowedips();
    }


    /**
     * Create an instance of {@link Amounttype }
     * 
     */
    public Amounttype createAmounttype() {
        return new Amounttype();
    }

    /**
     * Create an instance of {@link Extensiontype }
     * 
     */
    public Extensiontype createExtensiontype() {
        return new Extensiontype();
    }

    /**
     * Create an instance of {@link Commonattributestype }
     * 
     */
    public Commonattributestype createCommonattributestype() {
        return new Commonattributestype();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Schedulertype }
     * 
     */
    public Schedulertype createSchedulertype() {
        return new Schedulertype();
    }

}
