//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.11 at 08:04:30 PM EAT 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "https://namaraka.com/bizlogic/model/v1_0")
@javax.xml.bind.annotation.XmlSchema(namespace = "http://namaraka.com/ggserver/model/v1_0")
package com.namaraka.ggserver.model.v1_0;
